version: 0.2
env:
  variables:
    AWS_REGION: ap-southeast-2
    REPO_NAME: lab-flask
phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_URI}
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
  build:
    commands:
      - docker build -f Dockerfile -t ${ECR_URI}/${REPO_NAME}:${IMAGE_TAG} .
  post_build:
    commands:
      - docker push ${ECR_URI}/${REPO_NAME}:${IMAGE_TAG}
      - printf '[{"name":"flask","imageUri":"%s/%s:%s"}]' ${ECR_URI} ${REPO_NAME} ${IMAGE_TAG} > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json